/**
 * generated by Xtext 2.19.0
 */
package xtext.insa;

import xtext.insa.AbstractQcmRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class QcmRuntimeModule extends AbstractQcmRuntimeModule {
}
