/**
 * generated by Xtext 2.19.0
 */
package xtext.insa;

import xtext.insa.QcmStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class QcmStandaloneSetup extends QcmStandaloneSetupGenerated {
  public static void doSetup() {
    new QcmStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
