/*
 * generated by Xtext 2.19.0
 */
package xtext.insa.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import xtext.insa.QcmRuntimeModule
import xtext.insa.QcmStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class QcmIdeSetup extends QcmStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new QcmRuntimeModule, new QcmIdeModule))
	}
	
}
