/*
 * generated by Xtext 2.19.0
 */
package xtext.insa


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class QcmStandaloneSetup extends QcmStandaloneSetupGenerated {

	def static void doSetup() {
		new QcmStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
