/*
 * generated by Xtext 2.19.0
 */
package xtext.insa.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.insa.parser.antlr.internal.InternalQcmParser;
import xtext.insa.services.QcmGrammarAccess;

public class QcmParser extends AbstractAntlrParser {

	@Inject
	private QcmGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalQcmParser createParser(XtextTokenStream stream) {
		return new InternalQcmParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Qcm";
	}

	public QcmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(QcmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
