/**
 * generated by Xtext 2.19.0
 */
package xtext.insa.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import xtext.insa.ui.AbstractQcmUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class QcmUiModule extends AbstractQcmUiModule {
  public QcmUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
