/**
 * generated by Xtext 2.19.0
 */
package xtext.insa.ide;

import xtext.insa.ide.AbstractQcmIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class QcmIdeModule extends AbstractQcmIdeModule {
}
