/**
 * generated by Xtext 2.19.0
 */
package xtext.insa.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import xtext.insa.QcmRuntimeModule;
import xtext.insa.QcmStandaloneSetup;
import xtext.insa.ide.QcmIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class QcmIdeSetup extends QcmStandaloneSetup {
  @Override
  public Injector createInjector() {
    QcmRuntimeModule _qcmRuntimeModule = new QcmRuntimeModule();
    QcmIdeModule _qcmIdeModule = new QcmIdeModule();
    return Guice.createInjector(Modules2.mixin(_qcmRuntimeModule, _qcmIdeModule));
  }
}
