/*
 * generated by Xtext 2.19.0
 */
package xtext.insa.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtext.insa.qcm.ui.internal.QcmActivator;

public class QcmUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return QcmActivator.getInstance().getInjector("xtext.insa.Qcm");
	}

}
