/**
 * generated by Xtext 2.19.0
 */
package xtext.insa.ui.contentassist;

import xtext.insa.ui.contentassist.AbstractQcmProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class QcmProposalProvider extends AbstractQcmProposalProvider {
}
