/**
 * generated by Xtext 2.19.0
 */
package xtext.insa.validation;

import xtext.insa.validation.AbstractQcmValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class QcmValidator extends AbstractQcmValidator {
}
