/*
 * generated by Xtext 2.19.0
 */
package xtext.insa.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQcmScopeProvider extends DelegatingScopeProvider {
}
